"""Binary codec for AutomationDirect CLICK PLC ladder clipboard format."""

from .csv import read_csv
from .csv.writer import write_csv
from .decode import Rung, decode
from .decode_program import decode_program
from .encode import encode
from .instructions import (
    BlockCopy,
    Call,
    Coil,
    CompareContact,
    Contact,
    Copy,
    Counter,
    Drum,
    End,
    Fill,
    ForLoop,
    Math,
    ModbusAddress,
    ModbusRtuTarget,
    ModbusTcpTarget,
    Next,
    Pack,
    RawInstruction,
    Receive,
    Return,
    Search,
    Send,
    Shift,
    Timer,
    Unpack,
)
from .model import Program, Project

__all__ = [
    "encode",
    "decode",
    "decode_program",
    "read_csv",
    "write_csv",
    "Rung",
    "Program",
    "Project",
    "BlockCopy",
    "Call",
    "Contact",
    "CompareContact",
    "Counter",
    "Coil",
    "Drum",
    "Copy",
    "End",
    "Fill",
    "ForLoop",
    "Math",
    "Next",
    "ModbusAddress",
    "ModbusRtuTarget",
    "ModbusTcpTarget",
    "Pack",
    "Receive",
    "Send",
    "Timer",
    "Unpack",
    "RawInstruction",
    "Return",
    "Search",
    "Shift",
]
